# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 21:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_auto_20160120_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.date(2016, 1, 27)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='autor',
            name='direccion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='autor',
            name='fecha_nac',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='autor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.date(2016, 1, 27)),
            preserve_default=False,
        ),
    ]
